[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
addopts = -ra --alluredir=allure-results
markers =
    api: API-level tests
    ui: UI-only tests
    bdd: BDD-style tests
    hybrid: Hybrid UI + API tests
    e2e: Hybrid end-to-end tests
    smoke: Critical smoke tests
    regression: Regression tests
